version: '3.2'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "9000:9000"
    env_file:
      - .env   
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
        - "8080:80"
    depends_on:
      - laravel
    env_file:
      - .env   

      
networks:
  elk-monitoring:

volumes:
  elasticsearch:
